version: '3.8'
services:
  mongodb:
    build: ./mongodb
    container_name: shitchat-mongodb
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - shitchat-network

  api:
    build: ./api
    container_name: shitchat-api
    # ports:
    #   - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_NAME=shitchat
      - DB_HOST=mongodb:27017
    networks:
      - shitchat-network

  client:
    build: ./client
    container_name: shitchat-client
    ports:
      - "4000:4000"
    depends_on:
      - api
    environment:
      - PORT=4000
      - EXTERNAL_API_URI=http://api:3000
    networks:
      - shitchat-network

networks:
  shitchat-network:
    driver: bridge

volumes:
  mongodb_data:
